spring:
  application:
    name: audittrail

  # Database Connection Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/ledgerguard
    username: postgres
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true